AWSTemplateFormatVersion: "2010-09-09"
Resources:
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: JobsTable
      AttributeDefinitions:
        - AttributeName: JobId
          AttributeType: S
        - AttributeName: Status
          AttributeType: S
      KeySchema:
        - AttributeName: JobId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: Status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ExpirationTime
        Enabled: true
      Tags:
        - Key: Environment
          Value: Production

Outputs:
  JobsTableArn:
    Description: "ARN de la tabla de Jobs"
    Value: !GetAtt JobsTable.Arn
  JobsTableName:
    Description: "Nombre de la tabla de Jobs"
    Value: !Ref JobsTable
