Resources:
  GoLambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
        BuildMethod: makefile
    Properties:
      Handler: main
      Runtime: go1.x
      MemorySize: 512
      Timeout: 15
      Architectures:
        - x86_64  
      CodeUri: .
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /your-path
            Method: GET  # Puedes cambiar el método según lo necesites
            RestApiId: !Ref GoApiGateway  

  GoApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: GoLambdaApi
      Description: API para invocar la Lambda GoLambdaFunction
