AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # Lambda Function
  GoLambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: main
      Runtime: go1.x
      MemorySize: 512
      Timeout: 35
      Architectures:
        - x86_64  
      CodeUri: .
      Events:
        ApiGateway: 
          Type: Api
          Properties:
            Path: /your-path
            Method: POST
            RestApiId: !Ref GoApiGateway
      Environment:
        Variables:
          JOB_QUEUE_URL: !Ref JobQueue
          JOB_RESULT_QUEUE_URL: !Ref JobResultQueue
          DYNAMO_TABLE_NAME: !Ref ProcessStateTable
          JOB_QUEUE_DOMPDF_URL: "https://sqs.us-east-1.amazonaws.com/575108961165/ColaTest"
          JOB_QUEUE_FPDF_URL: "https://sqs.us-east-1.amazonaws.com/575108961165/ColaTest"
          JOB_QUEUE_TCPDF_URL: "https://sqs.us-east-1.amazonaws.com/575108961165/ColaTest"
          LAMBDA_AWS_REGION: "us-east-1"
          TARGETS_FILE_PATH: "/var/task/targets.json"


  GoApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: GoLambdaApi
      Description: API para invocar la Lambda GoLambdaFunction

  JobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: JobQueue

  JobResultQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: JobResultQueue

  ProcessStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ProcessState
      AttributeDefinitions:
        - AttributeName: processId
          AttributeType: S
      KeySchema:
        - AttributeName: processId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiUrl:
    Description: "URL de la API Gateway"
    Value: !Sub "https://${GoApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/your-path"

  JobQueueUrl:
    Description: "URL de la SQS Job Queue"
    Value: !Ref JobQueue

  JobResultQueueUrl:
    Description: "URL de la SQS Job Result Queue"
    Value: !Ref JobResultQueue

  DynamoTableName:
    Description: "Nombre de la tabla DynamoDB"
    Value: !Ref ProcessStateTable
